# Generated by Django 2.1.8 on 2020-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesave',
            name='save_date',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
