# Generated by Django 2.1.8 on 2020-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200623_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesave',
            name='save_date',
            field=models.IntegerField(),
        ),
    ]
