# Generated by Django 2.1.8 on 2020-06-23 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200623_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesave',
            name='input_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
