# Generated by Django 2.1.8 on 2020-06-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timesave_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesave',
            name='save_date',
            field=models.IntegerField(default=0),
        ),
    ]
